"""add_openai_api_key

Revision ID: 284c0a9d58ee
Revises: 8c80bb6fdaab
Create Date: 2026-05-11 12:18:46.510148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284c0a9d58ee'
down_revision: Union[str, None] = '8c80bb6fdaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_api_key_encrypted', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('openai_api_key_encrypted')

    # ### end Alembic commands ###
