"""Initial migration

Revision ID: 524008be446a
Revises: 
Create Date: 2026-04-21 12:07:32.053147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524008be446a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_website', sa.String(length=500), nullable=True),
    sa.Column('product_one_liner', sa.String(length=500), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_motto', sa.String(length=500), nullable=True),
    sa.Column('product_pricing', sa.Text(), nullable=True),
    sa.Column('product_features', sa.JSON(), nullable=True),
    sa.Column('product_differentiators', sa.JSON(), nullable=True),
    sa.Column('product_brochure_path', sa.String(), nullable=True),
    sa.Column('product_brochure_extracted', sa.Text(), nullable=True),
    sa.Column('product_style_sample', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('decision_maker_title', sa.String(length=255), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('local_context', sa.String(length=500), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('email_length', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('resend_api_key_encrypted', sa.String(), nullable=True),
    sa.Column('resend_from_email', sa.String(length=255), nullable=True),
    sa.Column('resend_from_name', sa.String(length=255), nullable=True),
    sa.Column('gmail_access_token_encrypted', sa.String(), nullable=True),
    sa.Column('gmail_refresh_token_encrypted', sa.String(), nullable=True),
    sa.Column('gmail_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('gmail_connected', sa.Boolean(), nullable=False),
    sa.Column('gmail_email', sa.String(length=255), nullable=True),
    sa.Column('gmail_last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('domain_active_since', sa.DateTime(), nullable=True),
    sa.Column('emails_sent_today', sa.Integer(), nullable=False),
    sa.Column('warmup_reset_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Enum('unsubscribe', 'not_interested', 'bounce', 'manual', name='blacklist_reason'), nullable=True),
    sa.Column('source_reply_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'email', name='uq_blacklist_workspace_email')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='campaign_status'), nullable=False),
    sa.Column('tone_override', sa.String(length=50), nullable=True),
    sa.Column('cta_override', sa.Text(), nullable=True),
    sa.Column('custom_instructions_override', sa.Text(), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('emails_generated', sa.Integer(), nullable=False),
    sa.Column('emails_sent', sa.Integer(), nullable=False),
    sa.Column('replies_received', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'researching', 'generated', 'approved', 'rejected', 'sent', 'replied', 'suppressed', 'archived', name='lead_status'), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('motto_found', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'email', name='uq_workspace_email')
    )
    op.create_table('generated_emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('variation_group_id', sa.Uuid(), nullable=True),
    sa.Column('variation_index', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('edited_body', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('resend_email_id', sa.String(), nullable=True),
    sa.Column('generation_attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('generated_email_id', sa.Uuid(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('classification', sa.Enum('interested', 'not_interested', 'question', 'out_of_office', 'unsubscribe', 'redirect', 'unclear', 'unclassified', name='reply_classification'), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reasoning', sa.Text(), nullable=True),
    sa.Column('suggested_reply_subject', sa.String(length=500), nullable=True),
    sa.Column('suggested_reply_body', sa.Text(), nullable=True),
    sa.Column('suggested_reply_generated_at', sa.DateTime(), nullable=True),
    sa.Column('user_action', sa.Enum('pending', 'replied_agent', 'replied_manual', 'suppressed', 'snoozed', 'ignored', name='reply_user_action'), nullable=False),
    sa.Column('snooze_until', sa.DateTime(), nullable=True),
    sa.Column('user_replied_at', sa.DateTime(), nullable=True),
    sa.Column('user_sent_body', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['generated_email_id'], ['generated_emails.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'gmail_message_id', name='uq_workspace_gmail_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_events')
    op.drop_table('generated_emails')
    op.drop_table('leads')
    op.drop_table('campaigns')
    op.drop_table('blacklist')
    op.drop_table('audit_logs')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
