"""rename_gmail_to_source

Revision ID: 8c80bb6fdaab
Revises: 2e623dba45b7
Create Date: 2026-04-28 13:12:58.629726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c80bb6fdaab'
down_revision: Union[str, None] = '2e623dba45b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_events', schema=None) as batch_op:
        batch_op.drop_constraint('uq_workspace_gmail_message', type_='unique')
        batch_op.create_unique_constraint('uq_workspace_source_message', ['workspace_id', 'source_message_id'])
        batch_op.drop_column('gmail_thread_id')
        batch_op.drop_column('gmail_message_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail_message_id', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('gmail_thread_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('uq_workspace_source_message', type_='unique')
        batch_op.create_unique_constraint('uq_workspace_gmail_message', ['workspace_id', 'gmail_message_id'])

    # ### end Alembic commands ###
