"""add_footer_fields

Revision ID: 93fef3e18254
Revises: 524008be446a
Create Date: 2026-04-24 11:50:32.311902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fef3e18254'
down_revision: Union[str, None] = '524008be446a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('product_phone', sa.String(length=50), nullable=True))
    op.add_column('workspaces', sa.Column('product_demo_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'product_demo_link')
    op.drop_column('workspaces', 'product_phone')
    # ### end Alembic commands ###
